# This makes a couple small networking tweaks that are specific to the
# ephemeral cluster, on top of the target cluster networking definition.
# These values can be overridden at the site, type, etc levels as appropriate.
apiVersion: airshipit.org/v1alpha1
kind: NetworkCatalogue
metadata:
  name: networking

spec:
  # The catalogue should be overridden as appropriate for different kubernetes
  # clusters, e.g. ephemeral vs target vs tenant
  kubernetes:
    podCidr: "192.168.0.0/24"
    controlPlaneEndpoint:
      host: "10.23.25.101"
    apiserverCertSANs: "[10.23.25.101, 10.23.24.101]"
  
  ironic:
    provisioningIp: "10.23.24.101"
    dhcpRange: "10.23.24.200,10.23.24.250"

