---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-memcached
  labels:
    name: openstack-memcached-global
    component: memcached
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.osh.memcached
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.osh.memcached
      dest:
        path: .values.images.tags

    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.oslo_cache
      dest:
        path: .values.endpoints.oslo_cache
data:
  chart_name: openstack-memcached
  release: openstack-memcached
  namespace: openstack
  wait:
    timeout: 900
    labels:
      release_group: airship-openstack-memcached
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-openstack-memcached
  values:
    labels:
      server:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
  dependencies:
    - memcached-htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: memcached-htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.osh.memcached-htk
      dest:
        path: .source
data:
  chart_name: memcached-htk
  release: memcached-htk
  namespace: memcached-htk
  values: {}
  dependencies: []
...
