apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../function/k8scontrol-ha
#   - dex-apiserver/apiserver-certs-secret.yaml

# patchesJson6902:
# - target:
#     group: controlplane.cluster.x-k8s.io
#     version: v1alpha3
#     kind: KubeadmControlPlane
#     name: cluster-controlplane
#   path: dex-apiserver/oidc-apiserver-flags.json
