apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../type/multi-tenant/ephemeral/controlplane
  - ../../target/catalogues # NOTE: use target networking for this phase
  # TODO (dukov) It's recocommended to upload BareMetalHost objects separately
  # otherwise nodes will hang in 'registering' state for quite a long time
  - nodes
transformers:
  - ../../../../type/multi-tenant/ephemeral/controlplane/replacements
