---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: keystone
  replacement: true
  labels:
    name: keystone-type
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: keystone-global
      component: keystone
    actions:
      - method: replace
        path: .values.pod
  storagePolicy: cleartext
data:
  values:
    pod:
      replicas:
        api: 1
...
