---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-armada
  replacement: true
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: ucp-armada-global
    actions:
      - method: replace
        path: .source
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  wait:
    timeout: 1800
  source:
    type: local
    location: /airship-components/armada
    subpath: charts/armada
  values:
    images:
      tags:
        api: quay.io/airshipit/armada:latest-ubuntu_xenial
    pod:
      replicas:
        api: 1
...
