resources:
  - ../../../../../../airshipctl/manifests/function/baremetal-operator/
  - ../../../../../../airshipctl/manifests/function/hwcc
  - ../../../../function/clusterctl
  - ../../../../function/hostconfig-operator
  - ../../../../../../airshipctl/manifests/composite/flux-helm/
  - ../../../../../../airshipctl/manifests/function/helm-chart-collator/

commonLabels:
  airshipit.org/stage: initinfra
