---
schema: deckhand/DataSchema/v1
metadata:
  schema: metadata/Control/v1
  name: promenade/Docker/v1
  labels:
    application: promenade
data:
  $schema: http://json-schema.org/schema#
  type: object
  properties:
    config:
      type: object
  required:
    - config
  additionalProperties: false
