---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-tiller
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.tiller
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.ucp.tiller
      dest:
        path: .values.images.tags

data:
  chart_name: tiller
  release: ucp-tiller
  namespace: kube-system
  wait:
    timeout: 100
    labels:
      release_group: airship-ucp-tiller
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-ucp-tiller
  values: {}
  dependencies:
    - tiller-htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: tiller-htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.tiller-htk
      dest:
        path: .source
data:
  chart_name: tiller-htk
  release: tiller-htk
  namespace: tiller-htk
  values: {}
  dependencies: []
...
