apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../type/airship-core/shared/catalogues
  - hosts.yaml
  - ../generator/results

patchesStrategicMerge:
  - versions-airshipctl.yaml
  - networking.yaml
  - networking-ha.yaml
