---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-cinder
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: Deploy Cinder
  chart_group:
    - cinder-rabbitmq
    - cinder
