---
schema: pegleg/SoftwareVersions/v1
metadata:
  schema: metadata/Document/v1
  replacement: true
  name: software-versions
  labels:
    name: software-versions-airskiff
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: software-versions-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  images:
    ucp:
      armada:
        api: "quay.io/airshipit/armada:latest-ubuntu_bionic"
      deckhand:
        deckhand: "quay.io/airshipit/deckhand:latest-ubuntu_xenial"
      shipyard:
        shipyard: "quay.io/airshipit/shipyard:latest-ubuntu_xenial"
        shipyard_db_sync: "quay.io/airshipit/shipyard:latest-ubuntu_xenial"
        airflow: "quay.io/airshipit/airflow:latest-ubuntu_xenial"
        airflow_db_sync: "quay.io/airshipit/airflow:latest-ubuntu_xenial"
...
