---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-promenade
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: ucp-promenade-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data: {}
...
