---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-promenade-global
  layeringDefinition:
    abstract: true
    layer: global
  labels:
    name: ucp-promenade-global
  storagePolicy: cleartext
  substitutions:

    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.promenade
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.ucp.promenade
      dest:
        path: .values.images.tags

    # Endpoints

    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.identity
      dest:
        path: .values.endpoints.identity
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.kubernetesprovisioner
      dest:
        path: .values.endpoints.kubernetesprovisioner

    # Credentials

    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.keystone.admin
      dest:
        path: .values.endpoints.identity.auth.admin
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.promenade.keystone
      dest:
        path: .values.endpoints.identity.auth.user

    # Secrets
    - dest:
        path: .values.endpoints.identity.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_keystone_admin_password
        path: .
    - dest:
        path: .values.endpoints.identity.auth.user.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_promenade_keystone_password
        path: .

data:
  chart_name: promenade
  release: ucp-promenade
  namespace: ucp
  wait:
    timeout: 600
    labels:
      release_group: airship-ucp-promenade
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-ucp-promenade
  values:
    pod:
      replicas:
        api: 2
      env:
        promenade_api:
         # this aligns with drydocks timeouts and allows alow responses to
         # download the external kubernetes client .tgz to still succeed
         - name: UWSGI_TIMEOUT
           value: "900"
    conf:
      paste:
        filter:authtoken:
          paste.filter_factory: keystonemiddleware.auth_token:filter_factory
          admin_tenant_name: service
          admin_user: promenade
          delay_auth_decision: true
          identity_uri: http://keystone-api.ucp.svc.cluster.local/
          service_token_roles_required: true
  dependencies:
    - promenade-htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: promenade-htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.promenade-htk
      dest:
        path: .source
data:
  chart_name: promenade-htk
  release: promenade-htk
  namespace: promenade-htk
  values: {}
  dependencies: []
...
