---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: osh-infra-monitoring
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: OSH Infra Monitoring
  chart_group:
    - prometheus
    - prometheus-alertmanager
    - prometheus-node-exporter
    - prometheus-process-exporter
    - prometheus-kube-state-metrics
    - nagios
...
