---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: tenant-ceph-osd
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: tenant-ceph-osd-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data: {}
...
