---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-deckhand
  replacement: true
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: ucp-deckhand-global
    actions:
      - method: replace
        path: .source
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  wait:
    timeout: 1800
  source:
    type: local
    location: /airship-components/deckhand
    subpath: charts/deckhand
  values:
    images:
      tags:
        api: quay.io/airshipit/deckhand:latest-ubuntu_xenial
    pod:
      replicas:
        deckhand: 1
...
