apiVersion: airshipit.org/v1alpha1
kind: Clusterctl
metadata:
  labels:
    airshipit.org/deploy-k8s: "false"
  name: clusterctl-v1
init-options:
  core-provider: "cluster-api:v0.3.3"
  bootstrap-providers:
    - "kubeadm:v0.3.3"
  infrastructure-providers:
    - "metal3:v0.3.1"
  control-plane-providers:
    - "kubeadm:v0.3.3"
providers:
  - name: "metal3"
    type: "InfrastructureProvider"
    versions:
      v0.3.1: ../airshipctl/manifests/function/capm3/v0.3.1
  - name: "kubeadm"
    type: "BootstrapProvider"
    versions:
      v0.3.3: ../airshipctl/manifests/function/cabpk/v0.3.3
  - name: "cluster-api"
    type: "CoreProvider"
    versions:
      v0.3.3: ../airshipctl/manifests/function/capi/v0.3.3
  - name: "kubeadm"
    type: "ControlPlaneProvider"
    versions:
      v0.3.3: ../airshipctl/manifests/function/cacpk/v0.3.3
