---
# The purpose of this file is to define environment-specific parameters for
# ceph-osd
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: tenant-ceph-osd
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: tenant-ceph-osd-global
    actions:
      - method: replace
        path: .values.conf.storage.osd
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  values:
    labels:
      osd:
        node_selector_key: tenant-ceph-osd
        node_selector_value: enabled
    conf:
      storage:
        failure_domain: "rack"
        # NEWSITE-CHANGEME: The OSD count and configuration here should not need
        # to change if your HW matches the HW used in this environment.
        # Otherwise you may need to add or subtract disks to this list.
        # no need to create below jounal partitons as ceph charts will create them
        # default size of  journal partions is 10GB
        osd:
          - data:
              type: block-logical
              location: /dev/sde
            journal:
              type: block-logical
              location: /dev/sdb1
          - data:
              type: block-logical
              location: /dev/sdf
            journal:
              type: block-logical
              location: /dev/sdb2
          - data:
              type: block-logical
              location: /dev/sdg
            journal:
              type: block-logical
              location: /dev/sdc1
          - data:
              type: block-logical
              location: /dev/sdh
            journal:
              type: block-logical
              location: /dev/sdc2
      overrides:
        ceph_osd:
          hosts:
            - name: cab23-r720-14
              conf:
                storage:
                  failure_domain_name: "cab23_rack_1"
            - name: cab23-r720-17
              conf:
                storage:
                  failure_domain_name: "cab23_rack_2"
            - name: cab23-r720-19
              conf:
                storage:
                  failure_domain_name: "cab23_rack_3"
...
