---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: kubernetes-calico-etcd-global
  layeringDefinition:
    abstract: true
    layer: global
  labels:
    name: kubernetes-calico-etcd-global
  storagePolicy: cleartext
  substitutions:

    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.kubernetes.calico.etcd
      dest:
        path: .source

    # Image versions
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.calico.etcd
      dest:
        path: .values.images.tags

    # IP addresses
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .calico.etcd.service_ip
      dest:
        path: .values.service.ip
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .calico.etcd.service_ip
      dest:
        path: .values.anchor.etcdctl_endpoint

    # CAs
    - src:
        schema: deckhand/CertificateAuthority/v1
        name: calico-etcd
        path: .
      dest:
        path: .values.secrets.tls.client.ca
    - src:
        schema: deckhand/CertificateAuthority/v1
        name: calico-etcd-peer
        path: .
      dest:
        path: .values.secrets.tls.peer.ca

    # Anchor client cert
    - src:
        schema: deckhand/Certificate/v1
        name: calico-etcd-anchor
        path: .
      dest:
        path: .values.secrets.anchor.tls.cert
    - src:
        schema: deckhand/CertificateKey/v1
        name: calico-etcd-anchor
        path: .
      dest:
        path: .values.secrets.anchor.tls.key

data:
  chart_name: etcd
  release: kubernetes-calico-etcd
  namespace: kube-system
  protected:
    continue_processing: true
  wait:
    timeout: 600
    labels:
      release_group: airship-kubernetes-calico-etcd
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-kubernetes-calico-etcd
  values:
    labels:
      anchor:
        node_selector_key: calico-etcd
        node_selector_value: enabled
    etcd:
      host_data_path: /var/lib/etcd/calico
      host_etc_path: /etc/etcd/calico
    bootstrapping:
      enabled: true
      host_directory: /var/lib/anchor
      filename: calico-etcd-bootstrap
    service:
      name: calico-etcd
    network:
      service_client:
        name: service_client
        port: 6666
        target_port: 6666
      service_peer:
        name: service_peer
        port: 6667
        target_port: 6667
  dependencies:
    - kubernetes-calico-etcd-htk
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: kubernetes-calico-etcd-htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.kubernetes.calico.etcd-htk
      dest:
        path: .source
data:
  chart_name: kubernetes-calico-etcd-htk
  release: kubernetes-calico-etcd-htk
  namespace: kubernetes-calico-etcd-htk
  values: {}
  dependencies: []
...
