---
# NOTE: This file is ignored by Airskiff and is copied from the seaworthy site.

# The purpose of this file is to define environment-specific parameters for
# ceph-osd
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-ceph-osd
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: ucp-ceph-osd-global
    actions:
      - method: replace
        path: .values.conf.storage.osd
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  values:
    conf:
      storage:
        # NEWSITE-CHANGEME: The OSD count and configuration here should not need
        # to change if your HW matches the HW used in this environment.
        # Otherwise you may need to add or subtract disks to this list.
        # no need to create below jounal partitons as ceph charts will create them
        # default size of  journal partions is 10GB
        osd:
          - data:
              type: block-logical
              location: /dev/sdd
            journal:
              type: block-logical
              location: /dev/sdb1
          - data:
              type: block-logical
              location: /dev/sde
            journal:
              type: block-logical
              location: /dev/sdb2
          - data:
              type: block-logical
              location: /dev/sdf
            journal:
              type: block-logical
              location: /dev/sdb3
          - data:
              type: block-logical
              location: /dev/sdg
            journal:
              type: block-logical
              location: /dev/sdb4
          - data:
              type: block-logical
              location: /dev/sdh
            journal:
              type: block-logical
              location: /dev/sdc1
          - data:
              type: block-logical
              location: /dev/sdi
            journal:
              type: block-logical
              location: /dev/sdc2
          - data:
              type: block-logical
              location: /dev/sdj
            journal:
              type: block-logical
              location: /dev/sdc3
          - data:
              type: block-logical
              location: /dev/sdk
            journal:
              type: block-logical
              location: /dev/sdc4
...
