---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: kubernetes-controller-manager
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.kubernetes.controller-manager
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.kubernetes.controller-manager
      dest:
        path: .values.images.tags

    # Kube-controller-manager Log Level
    - src:
        schema: nc/CorridorConfig/v1
        name: corridor-config
        path: .kubernetes_components.controller_manager_log_level
      dest:
        path: .values.controller_manager.logging.log_level

    # IP addresses
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .kubernetes.pod_cidr
      dest:
        path: .values.network.pod_cidr
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .kubernetes.service_cidr
      dest:
        path: .values.network.service_cidr
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .kubernetes.pod_cidr
      dest:
        path: .values.command_prefix[2]
        pattern: SUB_POD_CIDR
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .kubernetes.service_cidr
      dest:
        path: .values.command_prefix[3]
        pattern: SUB_SERVICE_CIDR

    # CA
    - src:
        schema: deckhand/CertificateAuthority/v1
        name: kubernetes
        path: .
      dest:
        path: .values.secrets.tls.ca

    # Certificates
    - src:
        schema: deckhand/Certificate/v1
        name: controller-manager
        path: .
      dest:
        path: .values.secrets.tls.cert
    - src:
        schema: deckhand/CertificateKey/v1
        name: controller-manager
        path: .
      dest:
        path: .values.secrets.tls.key

    # Private key for Kubernetes service account token signing
    - src:
        schema: deckhand/PrivateKey/v1
        name: service-account
        path: .
      dest:
        path: .values.secrets.service_account.private_key

data:
  chart_name: controller-manager
  release: kubernetes-controller-manager
  namespace: kube-system
  protected:
    continue_processing: false
  wait:
    timeout: 900
    labels:
      release_group: clcp-kubernetes-controller-manager
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: clcp-kubernetes-controller-manager
  values:
    command_prefix:
      - /hyperkube
      - kube-controller-manager
      - --cluster-cidr=SUB_POD_CIDR
      - --service-cluster-ip-range=SUB_SERVICE_CIDR
      - --node-monitor-period=5s
      - --node-monitor-grace-period=20s
      - --pod-eviction-timeout=60s
      - --terminated-pod-gc-threshold=1000
    network:
      kubernetes_netloc: 127.0.0.1:6553
    pod:
      lifecycle:
        upgrades:
          daemonsets:
            pod_replacement_strategy: RollingUpdate
            kubernetes-controller-manager-anchor:
              enabled: true
              min_ready_seconds: 0
              max_unavailable: 50%
  dependencies:
    - controller-manager-htk
...
---
# Helm toolkit
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: controller-manager-htk
  layeringDefinition:
    abstract: false
    layer: global
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.kubernetes.controller-manager-htk
      dest:
        path: .source
  storagePolicy: cleartext
data:
  chart_name: controller-manager-htk
  release: controller-manager-htk
  namespace: controller-manager-htk
  timeout: 600
  wait:
    timeout: 600
  upgrade:
    no_hooks: true
  values: {}
  dependencies: []
...
