---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-ingress-controller
  labels:
    name: openstack-ingress-controller-global
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.osh.ingress
      dest:
        path: .source
    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.osh.ingress
      dest:
        path: .values.images.tags
data:
  chart_name: openstack-ingress-controller
  release: openstack-ingress-controller
  namespace: openstack
  wait:
    timeout: 900
    labels:
      release_group: clcp-openstack-ingress-controller
    resources:
      - type: deployment
        min_ready: 33%
    native:
      enabled: false
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: clcp-openstack-ingress-controller
  values:
    labels:
      server:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
      error_server:
        node_selector_key: openstack-control-plane
        node_selector_value: enabled
    pod:
      replicas:
        ingress: 2
        error_page: 2
      lifecycle:
        upgrades:
          deployments:
            pod_replacement_strategy: RollingUpdate
            rolling_update:
              max_unavailable: 50%
    endpoints:
      ingress:
        port:
          http:
            default: 80
          https:
            default: 443
          healthz:
            default: 10254
          stream:
            default: 10247
          profiler:
            default: 10245
          server:
            default: 8181
  dependencies:
    - openstack-ingress-htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-ingress-htk
  layeringDefinition:
    abstract: false
    layer: global
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.osh.ingress-htk
      dest:
        path: .source
  storagePolicy: cleartext
data:
  chart_name: openstack-ingress-htk
  release: openstack-ingress-htk
  namespace: openstack-ingress-htk
  timeout: 600
  wait:
    timeout: 600
  upgrade:
    no_hooks: true
  values: {}
  dependencies: []
...
