---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: openstack-compute-kit
  labels:
    name: openstack-compute-kit-chart-group-global
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: Deploy Nova, Neutron, Openvswitch, and Libvirt
  chart_group:
    - libvirt
    - openvswitch
    - neutron
    - nova
