---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: libvirt
  labels:
    name: libvirt-global
    component: libvirt
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.osh.libvirt
      dest:
        path: .source
    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.osh.libvirt
      dest:
        path: .values.images.tags
data:
  chart_name: libvirt
  release: libvirt
  namespace: openstack
  wait:
    timeout: 900
    labels:
      release_group: clcp-libvirt
    resources:
      - type: daemonset
        min_ready: 100%
    native:
      enabled: false
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: clcp-libvirt
  values:
    labels:
      agent:
        libvirt:
          node_selector_key: openstack-libvirt
          node_selector_value: kernel
    pod:
      lifecycle:
        upgrades:
          daemonsets:
            pod_replacement_strategy: RollingUpdate
            libvirt:
              max_unavailable: 100%
      mandatory_access_control:
        type: apparmor
        libvirt-libvirt-default:
          libvirt: localhost/libvirt-v1
    ceph_client:
      configmap: tenant-ceph-etc
      user_secret_name: pvc-tceph-client-key
  dependencies:
    - os-libvirt-htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: os-libvirt-htk
  layeringDefinition:
    abstract: false
    layer: global
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.osh.libvirt-htk
      dest:
        path: .source
  storagePolicy: cleartext
data:
  chart_name: os-libvirt-htk
  release: os-libvirt-htk
  namespace: os-libvirt-htk
  timeout: 600
  wait:
    timeout: 600
  upgrade:
    no_hooks: true
  values: {}
  dependencies: []
...
