apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../function/k8scontrol-ha/replacements
  - ../../../../../../../airshipctl/manifests/function/k8scontrol/replacements
