apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../function/network-policy
  - ../../../../../function/treasuremap-base-catalogues

transformers:
  - ../../../../../function/network-policy/calico/replacements

