---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-maas-global
  layeringDefinition:
    abstract: true
    layer: global
  labels:
    name: ucp-maas-global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.maas
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.ucp.maas
      dest:
        path: .values.images.tags

    # Drydock IPs
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .bootstrap.ip
      dest:
        path: .values.conf.drydock.bootaction_url
        pattern: '(DRYDOCK_IP)'
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .node_ports.drydock_api
      dest:
        path: .values.conf.drydock.bootaction_url
        pattern: '(DRYDOCK_PORT)'

    # MaaS IPs
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .bootstrap.ip
      dest:
        path: .values.conf.maas.url.maas_url
        pattern: '(MAAS_IP)'
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .node_ports.maas_api
      dest:
        path: .values.conf.maas.url.maas_url
        pattern: '(MAAS_PORT)'
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .node_ports.maas_api
      dest:
        path: .values.network.gui.node_port.port
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .node_ports.maas_proxy
      dest:
        path: .values.network.proxy.node_port.port

    # MaaS Config
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .dns.upstream_servers_joined
      dest:
        path: .values.conf.maas.dns.dns_servers
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .ntp.servers_joined
      dest:
        path: .values.conf.maas.ntp.ntp_servers
    - src:
        schema: deckhand/Passphrase/v1
        name: maas-region-key
        path: .
      dest:
        path: .values.secrets.maas_region.value

    # Endpoint substitutions
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.postgresql
      dest:
        path: .values.endpoints.maas_db
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ucp.maas_region_ui
      dest:
        path: .values.endpoints.maas_region_ui

    # Account and credential substitutions
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.postgres.admin
      dest:
        path: .values.endpoints.maas_db.auth.admin
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.maas.postgres
      dest:
        path: .values.endpoints.maas_db.auth.user
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.maas.postgres.database
      dest:
        path: .values.endpoints.maas_db.path
        pattern: DB_NAME
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: ucp_service_accounts
        path: .ucp.maas.admin
      dest:
        path: .values.endpoints.maas_region_ui.auth.admin

    # Secrets
    - dest:
        path: .values.endpoints.maas_region_ui.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_maas_admin_password
        path: .
    - dest:
        path: .values.endpoints.maas_db.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_postgres_admin_password
        path: .
    - dest:
        path: .values.endpoints.maas_db.auth.user.password
      src:
        schema: deckhand/Passphrase/v1
        name: ucp_maas_postgres_password
        path: .
data:
  chart_name: maas
  release: maas
  namespace: ucp
  wait:
    timeout: 600
    labels:
      release_group: airship-maas
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-maas
  values:
    labels:
      rack:
        node_selector_key: maas-control-plane
        node_selector_value: enabled
      region:
        node_selector_key: maas-control-plane
        node_selector_value: enabled
    network:
      proxy:
        node_port:
          enabled: true
    conf:
      cache:
        enabled: true
      drydock:
        bootaction_url: http://DRYDOCK_IP:DRYDOCK_PORT/api/v1.0/bootactions/nodes/
      maas:
        credentials:
          secret:
            namespace: ucp
        url:
          maas_url: http://MAAS_IP:MAAS_PORT/MAAS
        proxy:
          proxy_enabled: 'false'
        ntp:
          use_external_only: 'true'
          disable_ntpd_region: true
          disable_ntpd_rack: true
        dns:
          require_dnssec: 'no'
  dependencies:
    - maas-htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: maas-htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.maas-htk
      dest:
        path: .source
data:
  chart_name: maas-htk
  release: maas-htk
  namespace: maas-htk
  values: {}
  dependencies: []
...
