---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: coredns
  layeringDefinition:
    abstract: false
    layer: global
  labels:
    name: coredns-global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.kubernetes.coredns
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.kubernetes.coredns
      dest:
        path: .values.images.tags

    # IP Addresses
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .dns.service_ip
      dest:
        path: .values.service.ip

    # Zones
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .dns.cluster_domain
      dest:
        path: .values.conf.coredns.corefile
        pattern: '(CLUSTER_DOMAIN)'
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .kubernetes.service_cidr
      dest:
        path: .values.conf.coredns.corefile
        pattern: '(SERVICE_CIDR)'
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .kubernetes.pod_cidr
      dest:
        path:  .values.conf.coredns.corefile
        pattern: '(POD_CIDR)'

    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .dns.upstream_servers[0]
      dest:
        path: .values.conf.coredns.corefile
        pattern: '(UPSTREAM1)'
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .dns.upstream_servers[1]
      dest:
        path: .values.conf.coredns.corefile
        pattern: '(UPSTREAM2)'

data:
  chart_name: coredns
  release: coredns
  namespace: kube-system
  protected:
    continue_processing: false
  wait:
    timeout: 900
    labels:
      release_group: clcp-coredns
  test:
    enabled: true
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: clcp-coredns
  values:
    conf:
      coredns:
        corefile: |
          .:53 {
              errors
              loadbalance round_robin
              health
              autopath @kubernetes
              kubernetes CLUSTER_DOMAIN SERVICE_CIDR POD_CIDR {
                pods insecure
                fallthrough in-addr.arpa ip6.arpa
                upstream UPSTREAM1
                upstream UPSTREAM2
              }
              prometheus :9253
              forward . UPSTREAM1 UPSTREAM2
              cache 30
              log . {
                class denial error
              }
          }
      test:
        names_to_resolve:
          - kubernetes.default.svc.cluster.local
    monitoring:
      prometheus:
        enabled: true
    pod:
      # TODO: replicas can be removed once we switch coredns to
      # DaemonSet-only.  It will be deployed with both DaemonSet
      # and Deployment-managed pods as we transition to DaemonSet.
      replicas:
        coredns: 2
    labels:
      coredns:
        # NOTE(mb874d): This is the label specified in the IPDD
        node_selector_key: kube-dns
        node_selector_value: enabled
    manifests:
      # NOTE(mc981n) Delay adding the coredns daemonset until after all
      #              the nodes have bootstraped/joined
      daemonset: false
      # TODO: `deployment` can be set to false once we switch coredns to
      # DaemonSet-only.  It will be deployed with both DaemonSet
      # and Deployment-managed pods as we transition to DaemonSet.
      deployment: true
  dependencies:
    - coredns-htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: coredns-htk
  layeringDefinition:
    abstract: false
    layer: global
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.kubernetes.coredns-htk
      dest:
        path: .source
  storagePolicy: cleartext
data:
  chart_name: coredns-htk
  release: coredns-htk
  namespace: coredns-htk
  timeout: 600
  wait:
    timeout: 600
  upgrade:
    no_hooks: true
  values: {}
  dependencies: []
...
