---
schema: promenade/Docker/v1
metadata:
  schema: metadata/Document/v1
  name: docker-global
  labels:
    promenade: enabled
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  config:
    live-restore: true
    storage-driver: overlay2
...
