---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: tenant-ceph-rgw
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.tenant-ceph-rgw
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.ceph.tenant-ceph-rgw
      dest:
        path: .values.images.tags

    # IP addresses
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .storage.ceph.public_cidr
      dest:
        path: .values.network.public
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .storage.ceph.cluster_cidr
      dest:
        path: .values.network.cluster

    # Endpoints
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.identity
      dest:
        path: .values.endpoints.identity
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: osh_endpoints
        path: .osh.object_store
      dest:
        path: .values.endpoints.object_store
    - src:
        schema: pegleg/EndpointCatalogue/v1
        name: ucp_endpoints
        path: .ceph.tenant_ceph_mon
      dest:
        path: .values.endpoints.ceph_mon

    # Credentials
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.keystone.admin
      dest:
        path: .values.endpoints.identity.auth.admin
    - src:
        schema: pegleg/AccountCatalogue/v1
        name: osh_service_accounts
        path: .osh.swift.keystone
      dest:
        path: .values.endpoints.identity.auth.swift

    # Secrets
    - dest:
        path: .values.endpoints.identity.auth.admin.password
      src:
        schema: deckhand/Passphrase/v1
        name: osh_keystone_admin_password
        path: .
    - dest:
        path: .values.endpoints.identity.auth.swift.password
      src:
        schema: deckhand/Passphrase/v1
        name: ceph_swift_keystone_password
        path: .

data:
  chart_name: tenant-ceph-rgw
  release: tenant-ceph-rgw
  namespace: openstack
  wait:
    timeout: 900
    labels:
      release_group: airship-tenant-ceph-rgw
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - type: job
          labels:
            release_group: airship-tenant-ceph-rgw
  values:
    labels:
      job:
        node_selector_key: tenant-ceph-control-plane
        node_selector_value: enabled
      rgw:
        node_selector_key: tenant-ceph-rgw
        node_selector_value: enabled
    endpoints:
      identity:
        namespace: openstack
      object_store:
        namespace: openstack
      ceph_mon:
        namespace: tenant-ceph
    deployment:
      ceph: true
      client_secrets: false
      rbd_provisioner: false
      cephfs_provisioner: false
      rgw_keystone_user_and_endpoints: true
    bootstrap:
      enabled: false
    pod:
      replicas:
        rgw: 2
    conf:
      rgw_ks:
        enabled: true
      config:
          #NOTE (portdirect): See http://tracker.ceph.com/issues/21226
          rgw_keystone_token_cache_size: '0'
    ceph_client:
      configmap: tenant-ceph-etc
    secrets:
      keyrings:
        admin: pvc-tceph-client-key
  dependencies:
    - tenant-ceph-htk
...
